### ISSUE TITLE
'build' path isn't taken into account

### ISSUE THREAD

**Issue by badescuga** [ClickSimply/cpp-wasm-loader#5] opened 2018-03-25 09:25 UTC
Although i pass the build path to the loader, it doesn't take it into account. Thus, my .wasm file ends up in the root of the project.

         {
            test: /\.(c|cpp)$/,
             use: {
            loader: 'cpp-wasm-loader',
            options: {
              // Path to your 'build' or 'dist' directory relative to project root
              buildPath: 'build',
            //    emccPath: './emsdk',
            //   emccFlags: ['-O3']
            }
          }
        }

**Comment by Kobzol** [comment] 2018-04-08 13:25
This parameter actually meant something different, but it was obsolete and wasn't used. What do you want to achieve? When you build your project with webpack, you want to store the .wasm files in a folder, for example `dist/wasm/*.wasm`?

**Comment by mziwisky** [comment] 2018-04-11 22:38
yeah, i want as you describe @Kobzol -- i have my webpack setup with a `publicPath: /__build__/`, so I need https://github.com/Kobzol/cpp-wasm-loader/blob/7fcdb4393fab2aeeacecdf1ed55ad564b0e75754/src/index.js#L19 to essentially become `wasmBinaryFile: '/__build__/' + wasmName` -- is there a way to achieve that, especially w/o explicitly re-specifying the `publicPath` for this loader?  I've never dug into the guts of a webpack loader before, but can the loader access the "globally" configured publicPath?

**Comment by mziwisky** [comment] 2018-04-11 23:01
looks like maybe `__webpack_public_path__` could be used

**Comment by mziwisky** [comment] 2018-04-11 23:12
guess not.  tried it, got "ReferenceError: __webpack_public_path__ is not defined".  still investigating.

**Comment by mziwisky** [comment] 2018-04-11 23:28
ah, maybe the problem isn't to set that `wasmBinaryFile` as i thought.  it seems the compiled js from `emcc` contains `var wasmBinaryFile = 'filename-without-publicPath.wasm';`.  so perhaps there's a flag that can be passed to `emcc` to resolve this...

**Comment by mziwisky** [comment] 2018-04-11 23:56
aha!  i think the key lies in injection the option `locateFile` into the Module of https://github.com/Kobzol/cpp-wasm-loader/blob/7fcdb4393fab2aeeacecdf1ed55ad564b0e75754/src/index.js#L18-L21

ref: https://kripken.github.io/emscripten-site/docs/api_reference/module.html#Module.locateFile

that's the idea, anyway, but actually that Module gets stringified later, so we can't just stick a function there (cuz functions get lost in JSON.stringify), we'd have to stick it in the template string that follows.  no big deal.  but the last missing piece is I still haven't figured out how to get the `publicPath` from inside the loader.

**Comment by only-cliches** [comment] 2018-08-07 22:49
Closing this issue since it's been resolved with  PR.

**Closed as completed by only-cliches** 2018-08-07 22:49 UTC
